### ISSUE TITLE
ApiError requires initialisation?

### ISSUE THREAD

**Issue by robmarkcole** [Clarifai/clarifai-python#91]
Attempting to reproduce [test_auth.py](https://github.com/Clarifai/clarifai-python/blob/master/tests/rest_tests/test_auth.py) in my own test env I get the error: 
```
raise(ApiError)

TypeError: __init__() missing 4 required positional arguments: 'resource', 'params', 'method', and 'response'
```
I see that the error is initialised [here](https://github.com/Clarifai/clarifai-python/blob/819327a03c1aa789ff8c45c2117160e07ca64699/clarifai/rest/grpc/grpc_json_channel.py) but I'm not sure how to init in my test scenario ([here](https://github.com/home-assistant/home-assistant/pull/16814))

**Comment by rok-povsic** [comment]
@robmarkcole Hello Rob, the `ApiError` class wasn't really made to be instantiated outside of the library. But you can instantiate it if you provide the 4 required parameters. You can see [here](https://github.com/Clarifai/clarifai-python/blob/b1ced6e178d44ff88100f1e70fb3e2f1ce36f486/clarifai/errors.py#L15) which these are and how they are being used.

The 4 parameters are only used in logging so for your testing purposes, you can pass in dummy values. From the top of my head, you would create the `ApiError` object like this (note this hasn't been tested): 

```python
class FakeResponse:
    status_code = 404
    reason = 'Failure'
    def json(): return {}
resource = 'https://www.dummy.com/some/dummy/url'
params = {}
method = 'GET
response = FakeResponse()
```

Then in your `patch` call, you would _probably_ do something like this: 
```python
 .. side_effect=lambda: ApiError(resource, params, method, response)
```
Though take this with a grain of salt because I'm not familiar with the `patch` function that you use.

**Comment by robmarkcole** [comment]
@rok-povsic thanks! My solution is now:

```python
@pytest.fixture
def mock_app_with_error():
    """Throw an ApiError."""
    resource = 'https://www.mock.com/url'
    params = {}
    method = 'GET'
    response = MockErrorResponse()
    error = ApiError(resource, params, method, response)

    with patch('clarifai.rest.ClarifaiApp',
               side_effect=error) as _mock_mock_app_with_error:
        yield _mock_mock_app_with_error

def test_invalid_api_key(mock_app_with_error, caplog):
    """Test that an invalid api key is caught."""
    assert cg.validate_api_key(MOCK_API_KEY) is None
    assert "Clarifai error: API key not found" in caplog.text
```
tests passing, cheers!

**Comment by rok-povsic** [comment]
@robmarkcole Great, I'm glad it's working fine.

**Comment by rok-povsic** [comment]
@robmarkcole In the latest version 2.4.0, the `response` parameter of `ApiError` can now be None, so you can simplify your code by not needing the `FakeResponse` class/object.

**Comment by robmarkcole** [comment]
Excellent :-)
